### ISSUE TITLE
buttcoin counter should update live

### ISSUE THREAD

**Issue by psql** [jake/screenhole#40]

**Comment by jake** [comment]
one complication with this is if we want buttcoin balances to remain private, we need to stream the update specifically to the intended user. currently all the channels we use just broadcast everything to everyone. if we didn't do that, you'd theoretically be able to see someone else's balance by watching the websocket stream. 

two choices are:

1) figure out how to stream to specific users, and use that to stream the buttcoin balances per-user
2) decide we don't care about buttcoins being private

**Comment by psql** [comment]
I don’t think we need buttcoins to be “private”, but let’s just not show it in profiles and whatnot

Pasquale

**Comment by psql** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Animate Buttcoin count as ticker](https://trello.com/c/VRzAKPC2/10-animate-buttcoin-count-as-ticker)
