### ISSUE TITLE
Save place in feed when navigating away

### ISSUE THREAD

**Issue by psql** [jake/screenhole#42]
this requires a little bit of clever engineering, but any plans to save your place in the feed when going into/out-of grabs?

- @ian_dot_exe

**Comment by psql** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Save place in feed when navigating away to permalinks](https://trello.com/c/ghA4at4K/18-save-place-in-feed-when-navigating-away-to-permalinks)

**Comment by pugson** [comment]
Is there a router library for Vue? Should be fairly easy to do.

**Comment by pugson** [comment]
Temp fixed with https://github.com/jake/screenhole-web/commit/013bf785afcef98afe6e1acdf052d659f2311260
