### ISSUE TITLE
Backfill data for activity

### ISSUE THREAD

**Issue by psql** [jake/screenhole#58]
from @jake:
> wanna take a stab at backfilling the data @getaclue? just making a migration that loops over some queries
> the migrations auto run when we deploy so its easy to promote to prod that way

**Comment by getaclue00** [comment]
yo @jake I need some clarification on this plz

I'm assuming this work is to address [this](https://github.com/jake/screenhole-api/blob/master/app/controllers/memos_controller.rb#L96), ya?

**Comment by jake** [comment]
yeah, would be nice to backfill everyones activity feed with memos that had already been left before we started tracking notes for memos.

also, @pugson pointed out we need the `grab_id` to link the memo. so I thought for this task, we should just drop _all_ memo notes and regenerate them, setting the `grab_id` properly.
