### ISSUE TITLE
[TOP PRIORITY PLEASE DO] migrate serializers to fast_jsonapi

### ISSUE THREAD

**Issue by jake** [jake/screenhole#70]
`acive_model_serializer` is causing a lot of OOM issues, we need to migrate to `fast_jsonapi` as it seems to be better. (or alternatively, figure out why AMS is causing so many OOM errors?)

-> https://github.com/Netflix/fast_jsonapi

**Comment by vipinkosuri** [comment]
_I am new to rails and after trying to do this I understood this is beyond my skill level_ 

Current API gives the following response because of the setting `ActiveModelSerializers.config.adapter = :json` 

> {"user":{"id":"b9YtZb","username":"jacob","created_at":"2019-01-16T13:50:32.644Z","gravatar_hash":"1af159fd3e64c0df2c68af450750ff20","name":null,"bio":null,"blocked":[],"stats":{"grabs":0},"roles":["admin"]}}

Should have been this which gives similar response to FastJSON
`ActiveModelSerializers.config.adapter = :json_api` 

> {"data":{"id":"1","type":"users","attributes":{"username":"jacob","created-at":"2019-01-16T13:50:32.644Z","gravatar-hash":"1af159fd3e64c0df2c68af450750ff20","name":null,"bio":null,"blocked":[],"stats":{"grabs":0},"roles":["admin"]}}}


Took me two hours just to understand this, would like to see how to solve this if somebody does it :)

**Comment by jake** [comment]
thanks for taking a stab! you're right that the format is considerably different 🤔 

keep in mind, we are currently getting a hammered with out of memory issues. I traced it back to the serializers (via skylight.io), so the only objective for this is to solve that. if we can improve the performance some other way, im open

**Comment by anulman** [comment]
Hello friendly internet strangers! Stumbled on Screenhole this evening, and it just so happens I have the JSON-API experience this ticket needs, but not the time to ship it. My 2-person team is in crunch on a product launch—where our UI pipes JSON-API into React + Redux.

Still, I'd like to be of service. If helpful, I would be happy to grant a maintainer or two access to our code (and link relevant source!); or to find 30m - 60m to pair, working to break this hairy migration into tractable chunks. Beyond those, I'm open to suggestions. Let's slay those OOMs!
